language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python -m pip install --upgrade pip # https://github.com/scipy/scipy/issues/6213
  - pip install -r dev_requirements.txt
# command to run tests
script:
  - nosetests
  - ./docbuild.sh