language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install --upgrade pip setuptools wheel nose
  - pip install --only-binary=numpy,scipy numpy scipy
install:
  - python setup.py install
  - pip install sphinx sphinx_rtd_theme matplotlib codecov
  - pip install GPy
script:
  - nosetests --debug=DEFAULT --with-coverage
  - ./docbuild.sh
after_success:
  - codecov