language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
before_install:
  - pip install -U pip
  - pip install nose
install:
  - python setup.py install
  - pip install matplotlib
  - pip install GPy
script:
  - nosetests
